#!/bin/sh

. bincommon

FIND_PATTERN=
GREP_PATTERN=
SEARCH_DIR="."

usage ()
{
	echo "$PROGNAME prints lines matching GREP_PATTERN from files matching FIND_PATTERN."
	echo ""
	echo "Usage:"
	echo "  $PROGNAME [OPTIONS] FIND_PATTERN GREP_PATTERN"
	echo "Options:"
	echo "  -d DIR    where to search (default: .)"
}

while [ $# -gt 0 ]; do
	case "$1" in
		"-?"|--help)
			usage
			exit 0;;
		-d)
			SEARCH_DIR="$2"
			shift;;
		*)
			if [ -z "$FIND_PATTERN" ]; then
				FIND_PATTERN="$1"
			elif [ -z "$GREP_PATTERN" ]; then
				GREP_PATTERN="$1"
			else
				elog "too many arguments"
			fi
			;;
	esac
	shift
done

if [ -z "$FIND_PATTERN" -o -z "$GREP_PATTERN" ]; then
	elog "FIND_PATTERN and GREP_PATTERN must be required"
fi

find $SEARCH_DIR -name "$FIND_PATTERN" -exec grep -Hn "$GREP_PATTERN" {} \;
